#include <stdlib.h> // pour les fonctions exit, malloc, free, ...
#include <math.h> // pour les fonctions mathématiques comme sqrt, pow, ...
#include <stdio.h> // pour les fonctions d'entrée/sortie comme printf, scanf, stdin 
#include <unistd.h> // pour sleep (en millisecondes)
#include <string.h> // pour les chaines de char ( strlen, strcpy, strcat, strcmp, ...)
#include <time.h> // pour les fonctions comme time, rand, srand, ...

// Les fonctions